
apiVersion: v1
kind: Service
metadata:
  name: "{{.Chart.Name}}-service"
spec:
  type: {{ .Values.service.type }} # 참조 시 첫글자 대문자
  selector:
    app: member-app
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.containerPort }}